name: build

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gover: ['1.15.x', '1.16.x', '1.17.x' ]
    steps:
      - name: Set up Go ${{ matrix.gover }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.gover }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run Go tests
        run: find . -name go.mod -execdir go test -v ./... \;

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pheelee/dyndns:1.0.0,pheelee/dyndns:latest